name=tenergy32hub_adxl345
version=1.0.0
author=Tenergy Innovation
maintainer=Tenergy Innovation
sentence=Arduino library for ADXL345 accelerometer on tenergy32hub board
paragraph=This library provides an interface to communicate with the ADXL345 3-axis accelerometer using I2C communication protocol on the tenergy32hub ESP32 board.
category=Sensors
url=https://github.com/tenergyinnovation/tenergy32hub_adxl345
architectures=esp32
depends=Wire